const { MONGO_USER, MONGO_PWD, CURRENCY_LAYER_API_KEY, FIXER_API_KEY } = require('./local-keys')

module.exports = {
  MONGO_USER: process.env.MONGO_USER || MONGO_USER,
  MONGO_PWD: process.env.MONGO_PWD || MONGO_PWD,
  CURRENCY_LAYER_API_KEY: process.end.CURRENCY_LAYER_API_KEY || CURRENCY_LAYER_API_KEY,
  FIXER_API_KEY: process.env.FIXER_API_KEY || FIXER_API_KEY
}
